const $=s=>document.querySelector(s), arena=$('#game');
let state='ready',x=50,score=0,lives=3,level=1,combo=0,best=0,enemies=[],bullets=[],boss=null,spawnClock=0,shotClock=0,bossLevel=0,last=0,time=0,keys={};
try{best=Number(localStorage.getItem('tembakMantanBest'))||0}catch{}
let look='boy',muted=false,audio=null,hostile=[],powerClock=0,shield=0,invulnerable=0,bossShot=0;
function sprite(girl=false,bad=false){return `<svg viewBox="0 0 80 96" xmlns="http://www.w3.org/2000/svg"><path d="M23 45L15 84H65L57 45" fill="${bad?'#ef6595':'#8575ee'}" stroke="#241b32" stroke-width="3"/><path d="M28 80V94M52 80V94" stroke="#241b32" stroke-width="9"/><path d="M19 52L8 68M61 52L73 61" stroke="#efb896" stroke-width="9"/><rect x="64" y="43" width="13" height="23" rx="3" fill="#50d6ca" stroke="#241b32" stroke-width="3"/><path d="M17 35Q10 0 40 3Q70 0 63 40${girl?'L68 61H12Z':'Z'}" fill="#352438"/><ellipse cx="40" cy="28" rx="22" ry="23" fill="#efb896" stroke="#241b32" stroke-width="2"/><path d="M18 18Q26 -6 61 10L61 20Q45 11 36 13L21 23" fill="#352438"/><circle cx="31" cy="28" r="3"/><circle cx="49" cy="28" r="3"/><path d="M31 39Q40 ${bad?'30':'47'} 49 39" fill="none" stroke="#241b32" stroke-width="3"/></svg>`}
function sound(freq=600){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.start();o.stop(audio.currentTime+.08)}catch{}}
function effect(x,y,text){const e=entity('effect',x,y);e.el.textContent=text;setTimeout(()=>e.el.remove(),700)}
$('#mute').onclick=()=>{muted=!muted;$('#mute').textContent=muted?'Suara: OFF':'Suara: ON';$('#mute').setAttribute('aria-pressed',String(muted))};
$('#player').innerHTML=sprite();document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{look=b.dataset.look;$('#player').innerHTML=sprite(look==='girl');document.querySelectorAll('[data-look]').forEach(c=>c.setAttribute('aria-pressed',String(c===b)))});
const lines=['Aku berubah kok','Cuma kangen','Kita temenan aja','Salah kirim chat','Blokir berhasil'];
function hud(){$('#score').textContent=score;$('#lives').textContent='♥ '.repeat(lives)+'♡ '.repeat(3-lives);$('#level').textContent=level;$('#best').textContent=Math.max(best,score);$('#combo').textContent=combo+'×';$('#bossHud').hidden=!boss;if(boss)$('#bossHp').value=boss.hp}
function clear(){[...enemies,...bullets,...hostile].forEach(o=>o.el.remove());enemies=[];bullets=[];hostile=[];boss=null;keys={}}
function start(){clear();x=50;score=0;lives=3;level=1;combo=0;spawnClock=0;shotClock=0;bossLevel=0;time=0;powerClock=0;shield=0;invulnerable=0;bossShot=1;$('#player').classList.remove('shield');$('#characters').hidden=true;state='playing';$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').textContent='Jeda';$('#status').textContent='Tahan tembak. Jangan tahan perasaan.';render($('#player'),x,91);hud()}
function render(el,x,y){el.style.left=x+'%';el.style.top=y+'%'}
function entity(type,x,y){const el=document.createElement('div');el.className=type;arena.append(el);render(el,x,y);return {el,x,y}}
function spawn(){const e=entity('enemy',8+Math.random()*84,-5);e.el.innerHTML=sprite(Math.random()>.5,true)+'<span class="chat">'+['Kangen','Aku berubah','Cuma ngobrol','Balikan?'][Math.random()*4|0]+'</span>';sound(850);e.hp=1;e.phase=Math.random()*6;enemies.push(e)}
function spawnBoss(){boss=entity('enemy boss',50,12);boss.hp=8;boss.el.innerHTML=sprite(look!=='girl',true)+'<span class="chat">BALIKAN YUK!</span>';bossShot=1;enemies.push(boss);$('#status').textContent='Boss datang: mantan ngajak balikan!';hud()}
function shoot(){const spread=level>=2?[-12,0,12]:[0];for(const dx of spread){const b=entity('bullet',x,83);b.vx=dx;if(level>=2){b.el.classList.add('sandal');b.el.textContent='🩴'}bullets.push(b)}sound(420)}
function overlap(b,e){const w=arena.clientWidth,h=arena.clientHeight;return Math.abs(b.x-e.x)*w/100<(e.el.offsetWidth+b.el.offsetWidth)/2&&Math.abs(b.y-e.y)*h/100<(e.el.offsetHeight+18)/2}
function end(){state='over';best=Math.max(best,score);try{localStorage.setItem('tembakMantanBest',best)}catch{}clear();$('#overlay').hidden=false;$('#title').textContent='Healing dulu 💔';$('#description').textContent=`Skor ${score} · Rekor ${best}. Coba lagi, kamu bisa!`;$('#play').textContent='Main lagi';$('#pause').disabled=true;$('#status').textContent='Tarik napas. Lanjut move on.';hud()}
function pause(){if(state==='playing'){state='paused';keys={};$('#overlay').hidden=false;$('#title').textContent='Istirahat sebentar';$('#description').textContent='Skor dan nyawamu tetap aman.';$('#play').textContent='Lanjut main';$('#pause').textContent='Lanjut'}else if(state==='paused'){state='playing';$('#overlay').hidden=true;$('#pause').textContent='Jeda'}}
function tick(dt){time+=dt;invulnerable=Math.max(0,invulnerable-dt);shield=Math.max(0,shield-dt);$('#player').classList.toggle('shield',shield>0);powerClock+=dt;if(powerClock>12){powerClock=0;shield=4;effect(x,80,'BLOCK!');$('#status').textContent='Tameng BLOCK aktif 4 detik!'}if(boss){bossShot-=dt;if(bossShot<=0){bossShot=1.4;for(const dx of [-9,0,9]){const h=entity('hostile',boss.x,boss.y+10);h.vx=dx;h.el.textContent='♥';hostile.push(h)}sound(180)}}for(let i=hostile.length-1;i>=0;i--){const h=hostile[i];h.y+=35*dt;h.x+=h.vx*dt;render(h.el,h.x,h.y);if(Math.abs(h.x-x)*arena.clientWidth/100<24&&Math.abs(h.y-91)*arena.clientHeight/100<35){h.el.remove();hostile.splice(i,1);if(shield>0){effect(x,80,'DIBLOKIR!')}else if(invulnerable===0){lives--;invulnerable=1;arena.classList.add('damage');setTimeout(()=>arena.classList.remove('damage'),250);hud();if(lives===0){end();return}}}else if(h.y>105){h.el.remove();hostile.splice(i,1)}}x=Math.max(5,Math.min(95,x+((keys.right?1:0)-(keys.left?1:0))*65*dt));render($('#player'),x,91);shotClock-=dt;if(keys.fire&&shotClock<=0){shoot();shotClock=.18}spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=Math.max(.35,1.1-level*.055)}
 for(const e of enemies){if(e===boss){e.x=50+Math.sin(time*1.6)*28}else{e.y+=(9+level*1.2)*dt;e.x=Math.max(5,Math.min(95,e.x+Math.sin(time*3+e.phase)*8*dt))}render(e.el,e.x,e.y)}
 for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.y-=90*dt;b.x+=(b.vx||0)*dt;render(b.el,b.x,b.y);const target=enemies.find(e=>overlap(b,e));if(target){b.el.remove();bullets.splice(i,1);target.hp--;target.el.classList.add('hit');setTimeout(()=>target.el.classList.remove('hit'),100);if(target.hp<=0){effect(target.x,target.y,target===boss?'DITOLAK! 🧳':'DIBLOKIR!');sound(1000);combo++;score+=10+Math.min(combo,10);if(target===boss){score+=100;boss=null;$('#status').textContent='Balikan ditolak. Move on lanjut!'}else $('#status').textContent=lines[Math.random()*lines.length|0];target.el.remove();enemies.splice(enemies.indexOf(target),1);level=1+Math.floor(score/100);if(level>=2)$('#status').textContent='SANDAL SPREAD aktif!';arena.dataset.scene=level>=7?'wedding':level>=4?'cafe':'room'}hud()}else if(b.y<-5){b.el.remove();bullets.splice(i,1);combo=0;hud()}}
 for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e!==boss&&e.y>96){e.el.remove();enemies.splice(i,1);lives=Math.max(0,lives-1);combo=0;arena.classList.remove('damage');void arena.offsetWidth;arena.classList.add('damage');$('#status').textContent='Kenangan lolos. Nyawa berkurang!';hud();if(lives===0){end();return}}}if(level>=3&&!boss&&Math.floor(level/3)>bossLevel){bossLevel=Math.floor(level/3);spawnBoss()}}
function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;if(state==='playing')tick(dt);requestAnimationFrame(frame)}
$('#play').onclick=()=>state==='paused'?pause():start();$('#pause').onclick=pause;
const keyMap={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'fire'};document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'&&state!=='playing')return;if(keyMap[e.key]){e.preventDefault();keys[keyMap[e.key]]=true}if((e.key==='p'||e.key==='Escape')&&!e.repeat)pause()});document.addEventListener('keyup',e=>{if(keyMap[e.key])keys[keyMap[e.key]]=false});
for(const id of ['left','right','fire']){const b=$('#'+id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[id]=true};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys[id]=false}
window.addEventListener('blur',()=>{keys={};if(state==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});hud();render($('#player'),x,91);requestAnimationFrame(frame);
