const $=s=>document.querySelector(s),game=$('#game'),player=$('#player'),scoreEl=$('#score'),livesEl=$('#lives'),levelEl=$('#level'),bestEl=$('#best'),msg=$('#message'),statusEl=$('#status'),startBtn=$('#startBtn');
let x=50,score=0,lives=3,level=1,combo=0,running=false,keys={},enemies=[],bullets=[],timer,spawnTimer,boss=null;const lines=['red flag!','ghosting!','aku berubah kok','kita temenan aja','kamu terlalu baik 😭','salah kirim chat!'];bestEl.textContent=localStorage.getItem('tembakMantanBest')||0;
function update(){scoreEl.textContent=score;livesEl.textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);levelEl.textContent=level;bestEl.textContent=Math.max(score,+localStorage.getItem('tembakMantanBest')||0);player.style.left=`calc(${x}% - 24px)`}
function reset(){score=0;lives=3;level=1;combo=0;x=50;running=true;enemies.forEach(e=>e.el.remove());enemies=[];bullets=[];boss?.el.remove();boss=null;clearInterval(timer);clearInterval(spawnTimer);msg.innerHTML='';startBtn.textContent='RESTART';statusEl.textContent='Mode: jangan balikan.';update();spawnTimer=setInterval(spawn,Math.max(380,1050-level*65));timer=setInterval(loop,30);spawn()}
function spawn(){if(!running)return;const el=document.createElement('div');el.className='enemy';el.textContent=['💬','📸','💔','👻'][Math.random()*4|0];const e={el,x:Math.random()*90+5,y:-8,speed:.18+level*.035,hp:1};el.style.left=e.x+'%';el.style.top=e.y+'%';game.append(el);enemies.push(e)}
function bossUp(){if(boss||!running)return;const el=document.createElement('div');el.className='enemy boss';el.textContent='👤';boss={el,x:50,y:2,hp:8};el.style.cssText='left:50%;top:2%';game.append(el);popup(50,'BOSS: MANTAN NGAJAK BALIK!')}
function shoot(){if(!running)return;const el=document.createElement('div');el.className='bullet';el.textContent='💥';el.style.cssText=`left:calc(${x}% - 10px);bottom:74px`;game.append(el);bullets.push({el,y:84})}
function popup(pos,text){const p=document.createElement('div');p.className='pop';p.textContent=text;p.style.cssText=`left:${pos}%;bottom:35%`;game.append(p);setTimeout(()=>p.remove(),900)}
function hit(t){t.hp--;combo++;score+=10+Math.min(combo,10);if(t.hp<=0){t.el.remove();if(t===boss){boss=null;score+=100;level++;statusEl.textContent='Mantan tumbang!'}else enemies.splice(enemies.indexOf(t),1);if(score>=level*100){level++;if(level%3===0)bossUp()}}popup(t.x,combo>2?`COMBO x${combo}`:lines[Math.random()*lines.length|0]);update()}
function loop(){bullets.forEach((b,i)=>{b.y-=2.5;b.el.style.bottom=b.y+'%';const t=[...enemies,...(boss?[boss]:[])].find(e=>Math.abs(e.x-x)<8&&e.y>55);if(t){hit(t);b.el.remove();bullets.splice(i,1)}else if(b.y>105){b.el.remove();bullets.splice(i,1)}});enemies.forEach((e,i)=>{e.y+=e.speed;e.el.style.top=e.y+'%';if(e.y>86){e.el.remove();enemies.splice(i,1);combo=0;lives--;popup(x,'Duh, keinget lagi!');update();if(!lives)end()}});if(boss){boss.x=50+Math.sin(Date.now()/500)*20;boss.el.style.left=boss.x+'%'}}
function end(){running=false;clearInterval(timer);clearInterval(spawnTimer);enemies.forEach(e=>e.el.remove());bullets.forEach(b=>b.el.remove());enemies=[];bullets=[];if(boss){boss.el.remove();boss=null}const best=Math.max(score,+localStorage.getItem('tembakMantanBest')||0);localStorage.setItem('tembakMantanBest',best);msg.innerHTML=`GAME OVER 💔<br><small>Skor: ${score} • Best: ${best}</small>`;statusEl.textContent='Healing belum selesai.'}
document.addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();shoot()}});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);setInterval(()=>{if(!running)return;if(keys.arrowleft||keys.a)x=Math.max(4,x-1.5);if(keys.arrowright||keys.d)x=Math.min(96,x+1.5);update()},30);[['leftBtn','a'],['rightBtn','d']].forEach(([id,k])=>{const b=$('#'+id);b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointerleave=()=>keys[k]=false});$('#fireBtn').onpointerdown=shoot;startBtn.onclick=reset;
