const game=document.querySelector('#game'),player=document.querySelector('#player'),scoreEl=document.querySelector('#score'),livesEl=document.querySelector('#lives'),levelEl=document.querySelector('#level'),msg=document.querySelector('#message'),statusEl=document.querySelector('#status'),startBtn=document.querySelector('#startBtn');
let x=50,score=0,lives=3,level=1,running=false,keys={},enemies=[],timer,spawnTimer;
const insults=['red flag!','ghosting!','aku berubah kok','kita temenan aja','kamu terlalu baik 😭','salah kirim chat!'];
function reset(){score=0;lives=3;level=1;x=50;running=true;enemies.forEach(e=>e.el.remove());enemies=[];clearInterval(timer);clearInterval(spawnTimer);update();msg.innerHTML='';statusEl.textContent='Mode: jangan balikan.';startBtn.textContent='RESTART';spawnTimer=setInterval(spawn,Math.max(420,1100-level*100));timer=setInterval(loop,30);spawn();}
function update(){scoreEl.textContent=score;livesEl.textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);levelEl.textContent=level;player.style.left=`calc(${x}% - 24px)`}
function spawn(){if(!running)return;const el=document.createElement('div');el.className='enemy';el.textContent=['💬','📸','💔','👻'][Math.floor(Math.random()*4)];const e={el,x:Math.random()*90+5,y:-8,speed:0.18+level*.035};el.style.left=e.x+'%';el.style.top=e.y+'%';game.appendChild(el);enemies.push(e)}
function shoot(){if(!running)return;const b=document.createElement('div');b.className='bullet';b.textContent='💥';b.style.left=`calc(${x}% - 10px)`;b.style.bottom='74px';game.appendChild(b);let y=84;const iv=setInterval(()=>{y-=2.5;b.style.bottom=y+'%';const hit=enemies.findIndex(e=>Math.abs(e.x-x)<7 && e.y>65);if(hit>-1){const e=enemies.splice(hit,1)[0];e.el.remove();b.remove();clearInterval(iv);score+=10;if(score%100===0)level++;popup(x,insults[Math.floor(Math.random()*insults.length)]);update()}if(y>105){b.remove();clearInterval(iv)}},25)}
function popup(pos,text){const p=document.createElement('div');p.className='pop';p.textContent=text;p.style.left=pos+'%';p.style.bottom='35%';game.appendChild(p);setTimeout(()=>p.remove(),1000)}
function loop(){enemies.forEach((e,i)=>{e.y+=e.speed;e.el.style.top=e.y+'%';if(e.y>86){e.el.remove();enemies.splice(i,1);lives--;popup(x,'Duh, keinget lagi!');update();if(!lives)end()}})}
function end(){running=false;clearInterval(timer);clearInterval(spawnTimer);msg.innerHTML=`GAME OVER 💔<br><small>Skor kamu: ${score}<br>Mantan masih menang tipis.</small>`;statusEl.textContent='Healing belum selesai.'}
document.addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();shoot()}});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);setInterval(()=>{if(!running)return;if(keys.arrowleft||keys.a)x=Math.max(4,x-1.5);if(keys.arrowright||keys.d)x=Math.min(96,x+1.5);update()},30);startBtn.onclick=reset;
